### ISSUE TITLE
Estrelas e Badges

### ISSUE THREAD

**Issue by AlissonSteffens** [patrickgodinho/torcida-imperial#21]
Os usuários devem poder ganhar estrelas e badges
// TODO documento listando opções e regras

**Comment by gefymarcos** [comment]
Como posso ajudar com o desenvolvimento dessa issue?
Existe algum documento de regras ou design feito já?

estou a disposição pra ajudar vocês

**Comment by AlissonSteffens** [comment]
@gefymarcos a issue está atualmente na branch dev. Não existe ainda um documento oficial, mas temos algumas telas, vou ver com o pessoal se conseguimos passar para o git estas informações.
Vou marcar o @lucasSCsantos para ver se ele tem algo que possa ser postado aqui
